let g:before = [ '' ]

let g:tests = [ ['$hdaw'],
               \['dsF'  ],
               \['7|', 'dsf'  ],
               \['7|', 'dsF'  ],
               \['7|', 'csfhello'  ],
               \['7|', 'csFhello'  ],
               \['7|', 'ysfjf(lgsaf'  ],
               \['7|', 'ysfjf(lgsaF'  ],
               \['36|', 'cinmean'  ],
               \['36|', 'ciNyes'  ],
               \['36|', 'cifsmall()'  ],
               \['10|j', 'dsF'  ],
               \
               \['g{', '$hdaw'],
               \['g{', 'dsF'  ],
               \['g{', '7|', 'dsf'  ],
               \['g{', '7|', 'dsF'  ],
               \['g{', '7|', 'csfhello'  ],
               \['g{', '7|', 'csFhello'  ],
               \['g{', '7|', 'ysfjf{lgsaf'  ],
               \['g{', '7|', 'ysfjf{lgsaF'  ],
               \['g{', '36|', 'cinmean'  ],
               \['g{', '36|', 'ciNyes'  ],
               \['g{', '36|', 'cifsmall{}'  ],
               \['g{', '10|j', 'dsF'  ],
               \
               \['g[', '$hdaw'],
               \['g[', 'dsF'  ],
               \['g[', '7|', 'dsf'  ],
               \['g[', '7|', 'dsF'  ],
               \['g[', '7|', 'csfhello'  ],
               \['g[', '7|', 'csFhello'  ],
               \['g[', '7|', 'ysfjf[lgsaf'  ],
               \['g[', '7|', 'ysfjf[lgsaF'  ],
               \['g[', '36|', 'cinmean'  ],
               \['g[', '36|', 'ciNyes'  ],
               \['g[', '36|', 'cifsmall[]'  ],
               \['g[', '10|j', 'dsF'  ],
               \]

let g:after = [ '' ]
