let g:tests = [ [              "$hdaw"                  ],  
               \[              "dsF"                    ],  
               \[      "7|",   "dsf"                    ],  
               \[      "7|",   "dsF"                    ],  
               \[      "7|",   "csfhello"               ],  
               \[      "7|",   "csFhello"               ],  
               \[      "7|",   "ysfjf(lgsaf"            ],  
               \[      "7|",   "ysfjf(lgsaF"            ],  
               \[      "36|",  "cinmean"                ], 
               \[      "36|",  "ciNyes"                 ], 
               \[      "36|",  "cifsmall()"             ], 
               \[      "10|j", "dsF"                    ],
               \["g{",         "$hdaw"                  ],        
               \["g{",         "dsF"                    ],        
               \["g{", "7|",   "dsf"                    ],  
               \["g{", "7|",   "dsF"                    ],  
               \["g{", "7|",   "csfhello"               ],  
               \["g{", "7|",   "csFhello"               ],  
               \["g{", "7|",   "ysfjf{lgsaf"            ],  
               \["g{", "7|",   "ysfjf{lgsaF"            ],  
               \["g{", "36|",  "cinmean"                ], 
               \["g{", "36|",  "ciNyes"                 ], 
               \["g{", "36|",  "cifsmall{}"             ], 
               \["g{", "10|j", "dsF"                    ],
               \["g[",         "$hdaw"                  ],        
               \["g[",         "dsF"                    ],        
               \["g[", "7|",   "dsf"                    ],  
               \["g[", "7|",   "dsF"                    ],  
               \["g[", "7|",   "csfhello"               ],  
               \["g[", "7|",   "csFhello"               ],  
               \["g[", "7|",   "ysfjf[lgsaf"            ],  
               \["g[", "7|",   "ysfjf[lgsaF"            ],  
               \["g[", "36|",  "cinmean"                ], 
               \["g[", "36|",  "ciNyes"                 ], 
               \["g[", "36|",  "cifsmall[]"             ], 
               \["g[", "10|j", "dsF"                    ],
               \[              "gSiFhello\<CR>"         ],
               \[              "gSiwhello\<CR>, arg1"   ],
               \[      "20|",  "gSiwhello\<CR>, arg1"   ],
               \[      "2j",   "gSiFmulti\<CR>, ARG!"   ],
               \[              "gSiFnp.hello\<CR>"      ],
               \[      "12|",  "gS$dumb\<CR>, why...?"  ],
               \["g[", "12|",  "ysf$", "g(", "gsiF"     ],
               \["g{",         "dsF"                    ],
               \["g(",         "dsF"                    ],
               \["g(",         "dsF"                    ],
               \]

let g:before = [ "" ]                                   
let g:after = [ "" ]
